Finance-Manager-dev/FinanceManager/FinanceManager/urls.py
from django.contrib import admin
from django.urls import path, include
from fin_manager.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fin_manager.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', register, name='register'),
]

Finance-Manager-dev/FinanceManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("fin_manager.urls")),
]

Finance-Manager-dev/fin_manager/urls.py
#from django.conf.urls import url
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('expenses', name='expenses', view=views.ExpenseListView.as_view()),
    path('accounts/register/', views.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
]

Finance-Manager-dev/fin_manager/models.py
from django.db import models
from django.db.models import Sum, Count, F, Q
from datetime import datetime
from dateutil.relativedelta import relativedelta


class Account(models.Model):
    name = models.CharField(max_length=100)
    balance = models.FloatField(default=0)
    income = models.FloatField(default=0)
    expense = models.FloatField(default=0)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    saving_goal = models.FloatField(default=0)
    liability_list = models.ManyToManyField('Liability', blank=True)
    salary = models.FloatField(default=0)


class Liability(models.Model):
    name = models.CharField(max_length=100)
    amount = models.FloatField(default=0)
    date = models.DateField(null=False, default=datetime.now().date())
    long_term = models.BooleanField(default=False)
    interest_rate = models.FloatField(default=0, blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    monthly_expense = models.FloatField(default=0, blank=True, null=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    
    def save(self, *args, **kwargs):
        if self.long_term:
            self.monthly_expense = self.calculate_monthly_expense()
        super(Liability, self).save(*args, **kwargs)


    def calculate_monthly_expense(self):
        if self.long_term:
            if self.interest_rate == 0:
                return self.amount / ((self.end_date - self.date) / 30)  # Assuming a month has 30 days
            else:
                months = (self.end_date.year - datetime.now().year) * 12 + self.end_date.month - datetime.now().month
                monthly_rate = self.interest_rate / 12 / 100
                monthly_expense = (self.amount * monthly_rate) / (1 - (1 + monthly_rate) ** -months)
                return round(monthly_expense, 2)
        else:
            return self.monthly_expense

Finance-Manager-dev/fin_manager/forms.py
from django import forms
from .models import Liability


class LiabilityForm(forms.ModelForm):
    long_term = forms.BooleanField(required=False)  # Add the long_term field

    class Meta:
        model = Liability
        fields = ['name', 'amount', 'interest_rate', 'date', 'end_date', 'long_term']  # Include the long_term field

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control'}),
            'date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'interest_rate': forms.NumberInput(attrs={'class': 'form-control'}),
            'end_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'long_term': forms.CheckboxInput(attrs={'class': 'form-check-input'}),  # Style the checkbox if needed
        }

    def clean(self):
        cleaned_data = super().clean()
        long_term = cleaned_data.get('long_term')
        start_date = cleaned_data.get('date')
        if long_term:
            # If it's a long term liability, display all fields and calculate monthly_expense
            interest_rate = cleaned_data.get('interest_rate')
            end_date = cleaned_data.get('end_date')
            amount = cleaned_data.get('amount')
#            start_date = cleaned_data.get('date')
            cleaned_data['long_term'] = True
            # Calculate monthly_expense based on interest_rate and remaining months
            # You need to implement the calculation logic here

            #cleaned_data['monthly_expense'] = calculated_monthly_expense_value

        else:
            # If it's a one-time expense, hide unnecessary fields and set values to NULL
            cleaned_data['end_date'] = None
            cleaned_data['interest_rate'] = None

        return cleaned_data

Finance-Manager-dev/fin_manager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from fin_manager import models
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Count, F
from django.views.generic import TemplateView
from .models import Account, Liability
from .forms import LiabilityForm
from django.views.generic.edit import FormView
from django.views.generic import ListView
from django.utils.safestring import mark_safe
from datetime import datetime
from dateutil.relativedelta import relativedelta
import plotly.express as px
from plotly.graph_objs import *

def home(request):
    user = request.user    
    if user.is_authenticated:
        return redirect('expenses')
    else:
        return render(request, 'fin_manager/home.html')


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')  # Change 'home' to your desired URL
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def generate_graph(data):
    
    fig = px.bar(data, x='months', y='expenses', title='Monthly Expenses')
    fig.update_layout(
        xaxis=dict(rangeslider=dict(visible=True)),
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        font_color='rgba(0,0,0,1)',
    )
    fig.update_traces(marker_color='#008c41')

    graph_json = fig.to_json()

    return graph_json



class ExpenseListView(FormView):
    template_name = 'expenses/expense_list.html'
    form_class = LiabilityForm
    success_url = '/'  # Update this with the correct URL

    def form_valid(self, form):
        account, _ = Account.objects.get_or_create(user=self.request.user)
        
        liability = Liability(
            name=form.cleaned_data['name'],
            amount=form.cleaned_data['amount'],
            interest_rate=form.cleaned_data['interest_rate'],
            date=form.cleaned_data['date'],
            end_date=form.cleaned_data['end_date'],
            long_term=form.cleaned_data['long_term'],
            user=self.request.user
        )
        liability.save()
        account.liability_list.add(liability)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        accounts = Account.objects.filter(user=user)
        expense_data_graph = {}
        expense_data = {}

        for account in accounts:
            liabilities = account.liability_list.all()
            for liability in liabilities:
                if liability.long_term and liability.monthly_expense:
                    current_date = liability.date
                    while current_date <= liability.end_date:
                        year_month = current_date.strftime('%Y-%m')
                        if year_month not in expense_data_graph:
                            expense_data_graph[year_month] = []

                        expense_data_graph[year_month].append({
                            'name': liability.name,
                            'amount': liability.monthly_expense,
                            'date': current_date,
                            'end_date': liability.end_date,
                        })

                        # Move to the next month
                        current_date = current_date + relativedelta(months=1)
                else:
                    year_month = liability.date.strftime('%Y-%m')
                    if year_month not in expense_data_graph:
                        expense_data_graph[year_month] = []

                    expense_data_graph[year_month].append({
                        'name': liability.name,
                        'amount': liability.amount,
                        'date': liability.date,
                    })               

        for account in accounts:
            liabilities = account.liability_list.all()
            for liability in liabilities:
                if liability.long_term and liability.monthly_expense:
                    current_date = liability.date
                    year_month = current_date.strftime('%Y-%m')
                    if year_month not in expense_data:
                        expense_data[year_month] = []

                    expense_data[year_month].append({
                        'name': liability.name,
                        'amount': liability.monthly_expense,
                        'date': current_date,
                        'end_date': liability.end_date,
                        'long_term': liability.long_term,
                    })

                        # Move to the next month
                    current_date = current_date + relativedelta(months=1)
                else:
                    year_month = liability.date.strftime('%Y-%m')
                    if year_month not in expense_data:
                        expense_data[year_month] = []

                    expense_data[year_month].append({
                        'name': liability.name,
                        'amount': liability.amount,
                        'date': liability.date,
                    })              
        # Convert the expense_data_graph into aggregated_data
        aggregated_data = [{'year_month': key, 'expenses': sum(item['amount'] for item in value)} for key, value in expense_data_graph.items()]

        context['expense_data'] = expense_data
        context['aggregated_data'] = aggregated_data

        # Prepare graph_data for generating the Plotly graph
        graph_data = {
            'months': [item['year_month'] for item in aggregated_data],
            'expenses': [item['expenses'] for item in aggregated_data]
        }
        graph_data['chart'] = generate_graph(graph_data)
        context['graph_data'] = mark_safe(graph_data['chart'])  # Use mark_safe to render the JSON as HTML

        return context

Finance-Manager-dev/fin_manager/templates/expenses/expense_list.html
{% load static %}

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  
</head>

{% block content %}

<body>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function () {
      // Get a reference to the long_term checkbox and the fields to toggle
      var longTermCheckbox = $('#id_long_term');
      var longTermFields = $('#interest_rate, #end_date');

      // Initially hide the long_term fields
      longTermFields.hide();

      // Toggle the long_term fields based on checkbox selection
      longTermCheckbox.on('change', function () {
        if (longTermCheckbox.is(':checked')) {
          longTermFields.show();
        } else {
          longTermFields.hide();
        }
      });
    });
    </script>
    
    <div class="main">
      <div class="img">
      <img src="{% static 'images/logo.png' %}"
      </div>
    <div class="main-1">
      <div class="graph">
        <div class="bar-chart">
          <h2>Monthly Expenses Bar Chart</h2>
          <div class="plotly-chart" id="plotly-chart"></div>
        </div>

      </div>
      <div class="expense">
        <h2>Expense List</h2>

        <div class="expenses">
          {% for year_month, liabilities in expense_data.items %}
          <div class="month">
            <h3> Month: {{ year_month }}</h3>
            
              {% for liability in liabilities %}
              <div class="incomee">
                <div class="idhar">
                  <h2>{{ liability.name }}</h2>
                  {% if liability.long_term %}
                  <span class="date"> Date From: {{ liability.date }} <br>To: {{ liability.end_date }}</span>
                  {% else %}
                  <span class="date"> Date: {{ liability.date }}</span>
                  {% endif %}
                </div>
                <div class="udhar">
                  <h2>${{ liability.amount }}</h2>
                </div>
              
              </div>
              <br>
              {% endfor %}
            
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="lower">
      <div class="income">
        <h2>Add Long Term Liability or Daily Expense</h2>
        <form method="post">
          {% csrf_token %}
          {{ form.long_term.label_tag }}
          {{ form.long_term }}
          <br> <br>
          {{ form.name.label_tag }}
          {{ form.name }}
          {{ form.amount.label_tag }}
          {{ form.amount }}
          <br> <br>
          {{ form.date.label_tag }}
          {{ form.date }}
          <!-- Display long_term checkbox -->
          <br> <br>

          <!-- Display fields based on long_term value using if conditions -->
          <div id="end_date">
            {{ form.end_date.label_tag }}
            {{ form.end_date }}
          </div>
          <br>
          <div id="interest_rate">
            {{ form.interest_rate.label_tag }}
            {{ form.interest_rate }}
          </div>
          <br>
          <button type="submit" class="btn btn-success">Add Liability</button>
        </form>
        <!-- <div class="lower-2"><label for="saving-goal">Monthly Saving Goal:</label> -->
          <!-- <input type="number"style="margin-bottom:10px;" class="form-control" id="saving-goal" name="saving-goal" step="any"><br> -->
          <!-- <button id="set-saving-goal" class="btn btn-success">Set Saving Goal</button> -->
        </div>
      </div>
      
    </div>
  </div>


  <script>
    // Initialize the Plotly chart
    var graphData = {{ graph_data| safe }};
    Plotly.newPlot('plotly-chart', graphData.data, graphData.layout);
  </script>
</body>

{% endblock %}